name: CMake on a single platform

on:
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update apt
      run: sudo apt update
      
    - name: Install Software Properties Common Package
      run: sudo apt install software-properties-common

    - name: Add toolchain repository
      run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      
    - name: Install g++-12
      run: sudo apt install gcc-12 g++-12

    - name: Set default gcc and g++
      run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100 --slave /usr/bin/g++ g++ /usr/bin/g++-12

    - name: Check g++ version
      run: g++ --version
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/cmake-build-debug -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} # Ninja?

    - name: Build
      run: cmake --build ${{github.workspace}}/cmake-build-debug --config ${{env.BUILD_TYPE}}

    - name: MathTests
      working-directory: ${{github.workspace}}/cmake-build-debug
      run: ${{github.workspace}}/cmake-build-debug/MathTests

