name: CMake on a single platform

on:
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  formatting-check:
  
    name: Formatting Check
    
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Run clang-format style check for C/C++/Protobuf programs.
    
      uses: jidicula/clang-format-action@v4.11.0
      
      with:
        clang-format-version: '13'
        check-path: 'src'
        
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update apt
      run: sudo apt update
      
    - name: Install Software Properties Common Package
      run: sudo apt install software-properties-common

    - name: Add toolchain repository
      run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      
    - name: Install g++-12
      run: sudo apt install gcc-12 g++-12

    - name: Set default gcc and g++
      run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100 --slave /usr/bin/g++ g++ /usr/bin/g++-12

    - name: Check g++ version
      run: g++ --version
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/cmake-build-debug -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} # Ninja?

    - name: Build
      run: cmake --build ${{github.workspace}}/cmake-build-debug --config ${{env.BUILD_TYPE}}

    - name: Cache cmake-build-debug folder
      uses: actions/cache@v3
      with:
        path: |
          {{github.workspace}}/cmake-build-debug/
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: MathTests
      working-directory: ${{github.workspace}}/cmake-build-debug
      run: ${{github.workspace}}/cmake-build-debug/MathTests

