name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      
env:
  BUILD_TYPE: Release

permissions: write-all

jobs:
  tagged-release:
    name: "release"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v3

    # - name: Update apt
    #   run: sudo apt update
      
    # - name: Install Software Properties Common Package
    #   run: sudo apt install software-properties-common

    # - name: Add toolchain repository
    #   run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      
    # - name: Install g++-12
    #   run: sudo apt install gcc-12 g++-12

    # - name: Set default gcc and g++
    #   run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100 --slave /usr/bin/g++ g++ /usr/bin/g++-12

    # - name: Check g++ version
    #   run: g++ --version
      
    # - name: Configure CMake
    #   run: cmake -B ${{github.workspace}}/cmake-build-debug -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    # - name: Build
    #   run: cmake --build ${{github.workspace}}/cmake-build-debug --config ${{env.BUILD_TYPE}}

#    - name: Tar Xz source code
#      run: tar c src/ tests/ .clang-format CMakeLists.txt LICENSE README.md | xz > source.tar.xz
#
#    - name: Zip source code
#      run: zip -r source.zip src/ tests/ .clang-format CMakeLists.txt LICENSE README.md

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          LICENSE
